server:
  error:
    include-stacktrace: on_param


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cliente?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: banco123
  jpa:
    hibernate:
      ddl-auto: update